"""create searches and search runs tables

Revision ID: 9ff88057e982
Revises:
Create Date: 2026-08-05 21:52:42.601575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff88057e982'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('modality', sa.Enum('all', 'remote', 'hybrid', 'onsite', name='ck_searches_modality', native_enum=False, create_constraint=True), server_default='all', nullable=False),
    sa.Column('seniority', sa.Enum('all', 'trainee', 'junior', 'semi-senior', 'senior', name='ck_searches_seniority', native_enum=False, create_constraint=True), server_default='all', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='ck_search_runs_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('progress', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('total_found', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='ck_search_runs_progress_range'),
    sa.CheckConstraint('total_found >= 0', name='ck_search_runs_total_found_nonnegative'),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_runs_search_id'), 'search_runs', ['search_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_runs_search_id'), table_name='search_runs')
    op.drop_table('search_runs')
    op.drop_table('searches')
    # ### end Alembic commands ###
